"""
Chat endpoint.

WHAT: POST /api/chat endpoint
WHY: REST API for synchronous chat interactions
HOW: Delegate fully to OrchestratorAgent
"""

from fastapi import APIRouter, HTTPException

from ...shared.logger import (
    get_logger,
    generate_correlation_id,
    set_correlation_id,
)
from ..models import ChatRequest, ChatResponse
from ..dependencies import get_orchestrator

logger = get_logger(__name__)
router = APIRouter(tags=["chat"])


@router.post("/api/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    """
    Chat with the system.

    The gateway is intentionally thin:
    - Orchestrator owns sessions, routing, agents, synthesis
    """
    correlation_id = generate_correlation_id()
    set_correlation_id(correlation_id)

    logger.info(
        "Chat request received",
        query=request.query[:200],
        session_id=request.session_id,
    )

    try:
        orchestrator = get_orchestrator()

        final_response: str | None = None
        session_id: str | None = None
        agents_used: list[str] = []

        # 🔁 Stream orchestration events
        async for event in orchestrator.stream(request.query):
            event_type = event.get("type")

            if event_type == "analysis":
                # optional: inspect routing later
                pass

            elif event_type == "context":
                agent = event.get("agent")
                if agent and agent not in agents_used:
                    agents_used.append(agent)

            elif event_type == "final":
                if "error" in event:
                    raise HTTPException(
                        status_code=500,
                        detail=event["error"],
                    )

                data = event.get("data")
                if isinstance(data, dict):
                    # Expected shape from synthesize_response
                    final_response = data.get("synthesis")
                elif isinstance(data, str):
                    final_response = data

                session_id = event.get("session_id") or session_id

        if not final_response:
            raise HTTPException(
                status_code=500,
                detail="No response generated by orchestrator",
            )

        return ChatResponse(
            session_id=session_id or "generated-by-orchestrator",
            response=final_response,
            agents_used=agents_used or ["orchestrator"],
            correlation_id=correlation_id,
        )

    except HTTPException:
        raise
    except Exception as e:
        logger.error(
            "Chat request failed",
            error=str(e),
            correlation_id=correlation_id,
        )
        raise HTTPException(status_code=500, detail=str(e))
